# -*- coding: utf-8 -*-
"""bmi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GtDl5wyDd30UrCp-NdfQe99pG4p5KyH5
"""

from linebot import LineBotApi, WebhookHandler
from linebot.models import MessageEvent, TextMessage, TextSendMessage
from linebot.exceptions import LineBotApiError
from flask import Flask, request, abort

app = Flask(__name__)


line_bot_api = LineBotApi('hxEKQbraJfAIRasBKWRGBVk/oQCs0+NpP+7ybTG017VMwcssDwWdlttOe5k48KrYywlqxFgb83r63MFvi0ekwd6nLfxhegf6R15I0BCmPYtyiZbBnBjsgVPFJCa/LZG2hZEyunnVXFm1VXo1avdrWgdB04t89/1O/w1cDnyilFU=')


handler = WebhookHandler('070fb42b5cec5193b4ce54a2e8729cf8')


@app.route("https://linebot-ppv8.onrender.com/callback", methods=['POST'])
def callback():
    signature = request.headers['X-Line-Signature']
    body = request.get_data(as_text=True)
    app.logger.info("Request body: " + body)
    try:
        handler.handle(body, signature)
    except LineBotApiError as e:
        abort(400)
    return 'OK'


def calculate_bmi(height, weight):
    height_m = height / 100
    bmi = weight / (height_m ** 2)
    return bmi


@handler.add(MessageEvent, message=TextMessage)
def handle_message(event):
    user_message = event.message.text
    if user_message == "計算BMI":
        reply_message = "請輸入您的身高（公分）："
    elif user_message.isdigit():
        if "height" not in event.session:
            event.session["height"] = int(user_message)
            reply_message = "請輸入您的體重（公斤）："
        else:
            height = event.session.pop("height")
            weight = int(user_message)
            bmi = calculate_bmi(height, weight)
            reply_message = f"根據您的身高 {height} 公分和體重 {weight} 公斤，您的 BMI 為 {bmi:.2f}"
    else:
        reply_message = "請輸入數字。"
    line_bot_api.reply_message(event.reply_token, TextSendMessage(text=reply_message))

if __name__ == "__main__":
    app.run()